### ISSUE TITLE
Error while creating a new island

### ISSUE THREAD

**Issue by RokSoo** [BG-Software-LLC/SSB-AcidIslands#2]
### Minecraft's Version

paper-411 version 1.17.1

### Plugin's Version

SuperiorSkyblock2-1.9.0
addons SSBAcidisland-1.0.0
Generator.jar

### Describe the bug

i install the addons by following step on installation but it's seem i got some error with it, i can't make an island but if i delete the generator.jar i can make an island but in gamemode skyblock not acidisland
https://pastebin.com/bc7qWM0P

### To Reproduce

https://pastebin.com/bc7qWM0P

**Comment by OmerBenGera** [comment]
Fixed in latest dev build of SSB
