### ISSUE TITLE
AcidIslands generator bug

### ISSUE THREAD

**Issue by konfix** [BG-Software-LLC/SSB-AcidIslands#3]
### Minecraft's Version

1.19 paper (latest release)

### Plugin's Version

Latest dev build, 1.11.0-b720

### Describe the bug

Server crashes on start, generator can't load properly. After the crash it restarts and crashes again, that loops until you stop the server. I'm pretty sure that I uploaded everything correctly (Generator.jar to world-generator folder, AcidIslands to modules).

### To Reproduce

Stop the server, upload latest Generator.jar from jenkins, the server will crash on start.

### Additional Information

Error:
https://pastebin.com/eaJS4qEz
(I didn't change anything in configurations)

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
