### ISSUE TITLE
Couldn't register module

### ISSUE THREAD

**Issue by CachatYTC** [BG-Software-LLC/SSB-AcidIslands#4]
### Minecraft's Version

This server is running Purpur version git-Purpur-1171 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

### Plugin's Version

SuperiorSkyblock2 version 1.11.1.769

### Describe the bug

I got this error while trying to install AcidIslands module on lastest build of SuperiorSkyblock, generator works just fine but the module does not loading

### To Reproduce

Drag Generator.jar to world-generator in SuperiurSkyblock2 folder
Drag SSBAcidIslands-1.0.0-b4.jar to the modules in SuperiurSkyblock2 folder
restart the server

**Comment by OmerBenGera** [comment]
In the discord server you also sent a stack trace showing an error, where is it?
Upload it to pastebin and provide it here as well..

**Comment by CachatYTC** [comment]
https://pastebin.com/JtAGTkbw

**Comment by OmerBenGera** [comment]
Fixed in latest dev build of the module.
Also, please update SSB to latest dev build as well as otherwise it won't work.
