### ISSUE TITLE
Cannot create an island on water

### ISSUE THREAD

**Issue by LuluxClient** [BG-Software-LLC/SSB-AcidIslands#5]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-34 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3888607 on HEAD)
You are running 1 version beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.

### Plugin's Version

1.0.0b5

### Describe the bug

When adding the module and creating an island I will still be in the air without water on the ground, is there some steps to follow ? and I'm getting this error: https://pastebin.com/s5KXxXvK

### To Reproduce

Load the module, restart and boom you will never be on water. 

### Additional Information

I'm on 1.19.2 with a fresh install and getting this error: https://pastebin.com/s5KXxXvK

**Comment by LuluxClient** [comment]
Issue got fixed, forked some stuff and boom

**Comment by OmerBenGera** [comment]
You should have put the Generator jar inside the world generator folder.
