### ISSUE TITLE
 Bug report for AcidIsland module

### ISSUE THREAD

**Issue by Distolfix** [BG-Software-LLC/SSB-AcidIslands#8]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-61 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 47c34ca on HEAD)
You are running 8 versions beyond. Please update your server when possible to maintain stability, security, and receive the latest optimizations.
Previous version: git-Purpur-1933 (MC: 1.19.3)

### Plugin's Version

![image](https://user-images.githubusercontent.com/73421268/236791559-9d9a84d3-0ed8-4100-97db-85669232d57b.png)

### Describe the bug

Players are complaining that they take damage from water even when they are not in contact with it, let me explain it better. It seems that even though you are not actually in the water, you still take damage. Often, players take damage even when they are standing on a block above the water, causing problems for farming on the server.

As shown in the video I am sharing with you, you take damage even though you are above the layer of water (which shouldn't hurt). Additionally, you also take damage when you are holding down SHIFT, for example when expanding the island, and if you go to the edge while holding SHIFT, you take damage. This is not insignificant since after a while, the damage multiplier starts to increase.

### To Reproduce

https://youtu.be/t1PnaPYedw8

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it's better.

**Comment by Distolfix** [comment]
When i restart the server the module don't start.

**Comment by Distolfix** [comment]
https://pastebin.com/8KtxFBbp

**Comment by OmerBenGera** [comment]
> https://pastebin.com/8KtxFBbp

You put the Generator jar in the modules folder instead of the world-generator folder.

**Comment by Distolfix** [comment]
It works better, but you take damage on the farmland.

**Comment by Distolfix** [comment]
If you walk directly over the farmland, you take a lot of damage.

**Comment by OmerBenGera** [comment]
> If you walk directly over the farmland, you take a lot of damage.

You will take damage if you touch water, and because farmland are slightly lower than a full block, you will probably touch water.

**Comment by Distolfix** [comment]
I'm sorry, can't you make it so that you put the farmland block on a whitelist, like, on the farmland block you don't take damage?

**Comment by Distolfix** [comment]
And maybe add all the half blocks, so you don't take damage even if they are blocks divided into two?

**Comment by OmerBenGera** [comment]
> And maybe add all the half blocks, so you don't take damage even if they are blocks divided into two?

No, it makes no sense.
The whole point of the game mode is that you take damage in contact with water, no matter how you touch it.

**Comment by Distolfix** [comment]
You're right, but to fix this small issue, you could make it so that in the whitelist block, it checks the player's position relative to the water level. This way, even if it's halfway submerged, it won't attack the player. It's an idea.

**Comment by Distolfix** [comment]
Because, for example, on farmland, you don't touch the water, you touch the farmland. Your plugin detects water, but in reality, there is no water there.

**Comment by Distolfix** [comment]
Certainly, I understand what you mean. If you were to increase the damage or multiplier, players might complain because they wouldn't be able to efficiently farm on water. It's not an ideal situation for them.

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue persists let me know
